CRUD_Biblioteca/CRUD_Biblioteca/Models/Autor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CRUD_Biblioteca.Models
{
    public class Autor
    {
        public virtual int Id { get; set; }
        public virtual string Nome { get; set; }
    }
}

CRUD_Biblioteca/CRUD_Biblioteca/Models/AutorMap.cs
using FluentNHibernate.Mapping;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CRUD_Biblioteca.Models
{
    public class AutorMap : ClassMap<Autor>
    {
        public AutorMap(){
            Id(c => c.Id);
            Map(c => c.Nome);
            Table("Autores");
        }
    }
}

CRUD_Biblioteca/CRUD_Biblioteca/Models/ErrorViewModel.cs
using System;

namespace CRUD_Biblioteca.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CRUD_Biblioteca/CRUD_Biblioteca/Models/Livro.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CRUD_Biblioteca.Models
{
    public class Livro
    {
        public virtual int Id { get; set; }
        public virtual Autor Autor { get; set; }
        public virtual int QtdeEstoque { get; set; }

    }
}

CRUD_Biblioteca/CRUD_Biblioteca/Models/LivroMap.cs
using FluentNHibernate.Mapping;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CRUD_Biblioteca.Models
{
    public class LivroMap : ClassMap<Livro>
    {
        public LivroMap()
        {
            Id(c => c.Id);
            References(c => c.Autor);
            Map(c => c.QtdeEstoque);
            Table("Livros");
        }
    }
}

CRUD_Biblioteca/CRUD_Biblioteca/Controllers/AutorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CRUD_Biblioteca.Models;
using Microsoft.AspNetCore.Mvc;
using NHibernate;
using NHibernate.Linq;

namespace CRUD_Biblioteca.Controllers
{
    public class AutorController : Controller
    {
        private readonly ISession _session;

        public AutorController(ISession session)
        {
            _session = session;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _session.Query<Autor>().ToListAsync());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Autor autor )
        {
            if(ModelState.IsValid)
            {
                using(ITransaction transaction = _session.BeginTransaction())
                {
                    await _session.SaveAsync(autor);
                    await transaction.CommitAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(autor);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            return View(await _session.GetAsync<Autor>(id));
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, Autor autor)
        {
            if(autor.Id != id)
            {
                return NotFound();
            }

            if(ModelState.IsValid)
            {
                using(ITransaction transaction = _session.BeginTransaction())
                {
                    await _session.SaveOrUpdateAsync(autor);
                    await transaction.CommitAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(autor);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var autor = await _session.GetAsync<Autor>(id);

            using(ITransaction transaction = _session.BeginTransaction())
            {
                await _session.DeleteAsync(autor);
                await transaction.CommitAsync();
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

CRUD_Biblioteca/CRUD_Biblioteca/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CRUD_Biblioteca.Models;

namespace CRUD_Biblioteca.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CRUD_Biblioteca/CRUD_Biblioteca/Controllers/LivroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CRUD_Biblioteca.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NHibernate;
using NHibernate.Linq;

namespace CRUD_Biblioteca.Controllers
{
    public class LivroController : Controller
    {
        private readonly ISession _session;

        public LivroController(ISession session)
        {
            _session = session;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _session.Query<Livro>().ToListAsync());
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewData["Autores"] = new SelectList( _session.CreateQuery("select s from Autor s").List<Autor>().ToList(),
                "Id",
                "Nome"
            );
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Livro livro)
        {
            if (ModelState.IsValid)
            {
                using (ITransaction transaction = _session.BeginTransaction())
                {
                    await _session.SaveAsync(livro);
                    await transaction.CommitAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(livro);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            ViewData["Autores"] = new SelectList(_session.CreateQuery("select s from Autor s").List<Autor>().ToList(),
                   "Id",
                   "Nome"
               );
            return View(await _session.GetAsync<Livro>(id));
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, Livro livro)
        {
            if (livro.Id != id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                using (ITransaction transaction = _session.BeginTransaction())
                {
                    await _session.SaveOrUpdateAsync(livro);
                    await transaction.CommitAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(livro);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var livro = await _session.GetAsync<Livro>(id);

            using (ITransaction transaction = _session.BeginTransaction())
            {
                await _session.DeleteAsync(livro);
                await transaction.CommitAsync();
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

CRUD_Biblioteca/CRUD_Biblioteca/Views/Autor/Create.cshtml
@model CRUD_Biblioteca.Models.Autor

@{
    ViewData["Title"] = "Adicionar Autor";
}

<h4>Adicionar Autor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-outline-success btn-sm" /> &emsp;
                <a asp-action="Index" class="btn btn-link btn-sm">Voltar</a>
            </div>
        </form>
    </div>
</div>

CRUD_Biblioteca/CRUD_Biblioteca/Views/Autor/Index.cshtml
@model IEnumerable<CRUD_Biblioteca.Models.Autor>

@{
    ViewData["Title"] = "Lista de Autores";
}

    <h1>Lista de Autores</h1>

<p>
    <a asp-action="Create" class="btn btn-outline-success btn-sm">Adicionar Autor</a>
</p>
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                <a asp-controller="Autor" asp-action="Update" asp-route-Id="@item.Id" class="btn btn-outline-info btn-sm">
                    Atualizar
                </a> &emsp;
                <form asp-controller="Autor" asp-action="Delete" asp-route-Id="@item.Id" onclick="confirm('Deseja excluir o autor @item.Nome ?')">
                    <button type="submit" class="btn btn-outline-danger btn-sm">Excluir</button>
                </form>
            </td>
        </tr>
}
    </tbody>
</table>

CRUD_Biblioteca/CRUD_Biblioteca/Views/Autor/Update.cshtml
@model CRUD_Biblioteca.Models.Autor

@{
    ViewData["Title"] = "Atualizar Autor " + Model.Nome;
}

<h4>Atualizar Autor @Model.Nome</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Id" type="hidden" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Atualizar" class="btn btn-outline-info btn-sm" /> &emsp;
                <a asp-action="Index" class="btn btn-link btn-sm">Voltar</a>
            </div>
        </form>
    </div>
</div>

CRUD_Biblioteca/CRUD_Biblioteca/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CRUD_Biblioteca/CRUD_Biblioteca/Views/Livro/Create.cshtml
@model CRUD_Biblioteca.Models.Livro

@{
    ViewData["Title"] = "Adicionar Livro";
}

<h4>Adicionar Livro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Autor</label>
                @Html.DropDownListFor(
        x => x.Autor.Id,
        (IEnumerable<SelectListItem>)ViewData["Autores"]
    )
            </div>
                <div class="form-group">
                    <label asp-for="QtdeEstoque" class="control-label">Quantidade em Estoque</label>
                    <input asp-for="QtdeEstoque" class="form-control" />
                    <span asp-validation-for="QtdeEstoque" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Salvar" class="btn btn-outline-success btn-sm" /> &emsp;
                    <a asp-action="Index" class="btn btn-link btn-sm">Voltar</a>
                </div>
        </form>
    </div>
</div>

CRUD_Biblioteca/CRUD_Biblioteca/Views/Livro/Index.cshtml
@model IEnumerable<CRUD_Biblioteca.Models.Livro>

@{
    ViewData["Title"] = "Lista de Livros";
}

    <h1>Lista de Livros</h1>

<p>
    <a asp-action="Create" class="btn btn-outline-success btn-sm">Adicionar Livro</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Autor.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.QtdeEstoque)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <th>
                @Html.DisplayFor(modelItem => item.Autor.Nome)
            </th>
            <td>
                @Html.DisplayFor(modelItem => item.QtdeEstoque)
            </td>
            <td>
                <a asp-controller="Livro" asp-action="Update" asp-route-Id="@item.Id" class="btn btn-outline-info btn-sm">
                    Atualizar
                </a> &emsp;
                <form asp-controller="Livro" asp-action="Delete" asp-route-Id="@item.Id" onclick="confirm('Deseja excluir o livro ?')">
                    <button type="submit" class="btn btn-outline-danger btn-sm">Excluir</button>
                </form>
            </td>
        </tr>
}
    </tbody>
</table>

CRUD_Biblioteca/CRUD_Biblioteca/Views/Livro/Update.cshtml
@model CRUD_Biblioteca.Models.Livro

@{
    ViewData["Title"] = "Atualizar Livro";
}

<h4>Atualizar Livro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label class="control-label">Autor</label>
                @Html.DropDownListFor(
        x => x.Autor.Id,
        (IEnumerable<SelectListItem>)ViewData["Autores"]
    )
            </div>
            <div class="form-group">
                <label asp-for="QtdeEstoque" class="control-label"></label>
                <input asp-for="QtdeEstoque" class="form-control" />
                <span asp-validation-for="QtdeEstoque" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Atualizar" class="btn btn-outline-info btn-sm" /> &emsp;
                <a asp-action="Index" class="btn btn-link btn-sm">Voltar</a>
            </div>
        </form>
    </div>
</div>

CRUD_Biblioteca/CRUD_Biblioteca/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUD_Biblioteca</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRUD_Biblioteca</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Autor" asp-action="Index">Autor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Livro" asp-action="Index">Livro</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CRUD_Biblioteca - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>